### ISSUE TITLE
Question: do you have some more docs on "service objects" and HTTP class?

### ISSUE THREAD

**Issue by matthewsinclair** [mattgreen/elevate#5]
You mention in the readme "... when your tasks become complex, you can elect to extract them out to a service object." Do you have an example of what you mean there?

Also, do you have any docs for the "API" class which you say "is a thin wrapper class over Elevate::HTTP"?

I'd really like to use this framework, but I'm struggling to get started without an end-to-end example, or some more docs. Thanks.

Regards,
M@
# question

**Comment by mattgreen** [comment]
I've updated the README to remove the service object, as it obscures the example a bit. When I talk about a service object, basically I mean some sort of abstraction over your HTTP client. Like, an `API` class that handles issuing the request, and parsing the response. Elevate makes writing these much easier because it acts in a blocking manner. So it can definitely help you reify your API.

But you're right, examples speak the loudest. Will try to come up with some. Most of the things I use it in are closed source ATM. Will leave this open until examples are up.

**Comment by matthewsinclair** [comment]
Ok, thanks. Great work.

I'm going to try to come up with a simple example that uses Elevate in conjunction with a ViewController panel that manages a simple model object + service (or task set or some other name that I will come up with). If you're happy to review it for correctness, I'm happy for it to be used as an example. I've got a lot on my plate at the moment, so it might not be today ...

M@

**Comment by matthewsinclair** [comment]
Just looking at your Elevate::HTTP::HTTPClient class: I'm wondering how I specify additional header information. For example, once authenticated, I need to be able to send thru an API key. As far as I can tell, your #issue method is private, and so I can't add anything additional to the options hash to be passed thru as extra headers. Am I missing something?

**Comment by matthewsinclair** [comment]
Matt - I've now got my head around how to use the async task (I think) and I've also subclassed your `HTTPClient` in my own project so that I can pass in additional header variables, but now I'm trying to write a test and the async task is being starved from running such that the wait in the spec times out.

I wanted to isolate the tasks from the `ViewControllers` by putting them into their own `*Task` classes, which basically just provide a set of tasks, via a singleton instance for each of my model objects. 

For example, the TokenTasks class looks like this:

```
  class TokenTasks < ModelTaskBase
    def self.inst
      @@instance ||= self.new
    end

    # Given a email and password, attempt to get a new authentication token. If email/password
    # are valid, then the new authentication token is returned as #result. Note that if a valid
    # token is returned, it will automatically prime API with the new authentication_token value.
    def get_token_for(email, password, on_start=nil, on_update=nil, on_finish=nil)
      @get_token_for_task = async email: email, password: password do
        task do
          params = { user: { email: @email, password: @password} }
          resp   = API.inst.post("/tokens", params)
          if ModelTaskBase.is_valid?(resp)
            token = Token.new(resp.body[:response])
            API.inst.set_api_key(token.authentication_token)
            yield token
            token
          else
            raise ApiException.new(true), resp.body
          end
        end
      end
    end

  end # class TokenTasks
```

However, I can't seem to get the following spec to work:

```
  describe TokenTasks do
    # @run_on_main_thread = true

    it 'should provide a get_token_for task' do
      email    = 'matthew.sinclair@email.com'
      password = 'password'
      @task = TokenTasks.inst.get_token_for(
        email,
        password,
        proc {      puts "on_start" },
        proc {|s|   puts "on_update" },
        proc {|r,e| puts "on_finish"; resume }
      )
      NSLog "@task: #{@task.inspect}"
      @task.exception.should.equal nil

      wait_max 2.0 do
        @task.exception.should.equal nil
        token = @task.result
        token.class.should.be.same_as Token
        token.authentication_token.should.not.be nil
      end
    end # it
  end # describe
```

Even tho' `@task` contains an `"#<Elevate::ElevateOperation: >"` instance, none of the callbacks get executed prior the `wait_max` timing out. 

I notice in your test code that you monkey patched Bacon to include the Elevate stuff into `Contex`t, but I just want to keep things isolated and grab the `ElevateOperation` instance from `#get_token_for` and then work with.

Here's the output of that spec:

```
ake spec files=token_tasks_spec
     Build ./build/iPhoneSimulator-6.1-Development
     Build vendor/Pods
   Compile ./spec/models/tasks/token_tasks_spec.rb
      Link ./build/iPhoneSimulator-6.1-Development/T-Resources_spec.app/T-Resources
    Create ./build/iPhoneSimulator-6.1-Development/T-Resources_spec.dSYM
  Simulate ./build/iPhoneSimulator-6.1-Development/T-Resources_spec.app
TokenTasks
  - should provide a get_token_for task2013-07-04 18:32:11.475 T-Resources[58708:c07] @task: #<Elevate::ElevateOperation: >
 [FAILED - timeout exceeded: TokenTasks - should provide a get_token_for task]

Bacon::Error: timeout exceeded: TokenTasks - should provide a get_token_for task
    spec.rb:388:in `block in postponed_block_timeout_exceeded': TokenTasks - should provide a get_token_for task
    spec.rb:439:in `execute_block'
    spec.rb:388:in `postponed_block_timeout_exceeded'

1 specifications (1 requirements), 1 failures, 0 errors
```

What am I doing wrong here?

Thanks,
M@

**Comment by mattgreen** [comment]
You're not passing the callbacks into the task builder DSL.

Why not try this? Leave the Elevate task DSL to the controller, and write a service object that deals in pure domain logic:

``` ruby
module TokenTasks
  def self.get_token_for(email, password)
    params = { user: { email: @email, password @password } }

    response = API.inst.post("/tokens", params)
    if valid?(response)
      token = Token.new(response.body[:response])
      API.inst.set_api_key(token.authentication_token)

      token
    else
      raise ApiException.new(true), resp.body
    end
  end
end
```

Controller:

``` ruby
def login
  async username: @username.text, password: @password.text do
    task do
      TokenTasks.get_token_for(@username, @password)
    end

    on_start do
      puts 'Getting token...'
    end

    on_finish do |token, exception|
      puts 'Finished!'
    end
  end
end
```

I like this much, much more than the code you presented because your domain logic (the most important part of your app) is cleanly isolated from Elevate. Elevate should live inside the controller - it deals with all sorts of impure state relating to interacting with the real world! You can use something like WebStub to integration test the `TokenTasks` module. (You can just let it block like a normal integration test. The cancellation/timeout concerns are a controller-level responsibility.)

You may argue that your code is not completely isolated from Elevate, as it still makes HTTP requests through it. This is the reason you have an `API` class: so you can avoid exposing this detail to your domain logic.

For more information, read this: http://blog.8thlight.com/uncle-bob/2011/11/22/Clean-Architecture.html

**Comment by matthewsinclair** [comment]
Ok, I like that. I'll give it a go.

Just so I understand _why_ the spec wasn't working, what do you mean when you say "You're not passing the callbacks into the task builder DSL." Where did I get that bit wrong?

And thanks a lot for the help, by the way! Much appreciated.

Thanks,
M@

**Comment by mattgreen** [comment]
The outer `async` block is where you define your callbacks. Right now you just have `task` defined. You accept them as arguments with default values to `get_token_for`, but you don't do anything with them after that.

Really, the DSL is a bit heavy, but I'll have to look at it for next release.

**Comment by matthewsinclair** [comment]
Ok. Got it. By the way, that earlier tip has saved me _hours_. You're a legend. Thanks!

**Comment by matthewsinclair** [comment]
Matt - are the hash params provided to async available in the on_start and on_finish blocks?

**Comment by matthewsinclair** [comment]
On reflection, the question I have in addition to the one above is: how do you get access to the owning `ViewController` that the task is running in from within the handlers of the `async` task? `self` inside `task do` appears to be an instance of `Elevate::TaskContext` rather than the owning `ViewController`. 

I tried passing in a reference to the `ViewController` in the `async` hash, but as per the earlier question, none of the hash params passed into the `async` block seem to be available in the `on_start` or `on_finished` blocks.

I need to get the result of a remote call (which I am yielding from within `task`) back out to owning ViewController. I thought that the way to do that would be to set it back there once the block was finished. But I've obviously got that wrong.

The only way I can think to make this work is to pass the owning `ViewController` into the `task do` hash as a param, and then `yield` the controller at the end of that block so that it's available to `on_finish`. Is this crazy?

**Comment by mattgreen** [comment]
The Hash params are not available. This seems like an oversight to me.

Within the callbacks, `self` should be the context that called `async`, aka, your view controller.
