### ISSUE TITLE
Periodic task

### ISSUE THREAD

**Issue by tchukuchuk** [mattgreen/elevate#8]
Hi,

I would like to write a periodic task with BW::EM.add_periodic_timer , and I'm wondering if I can use Elevate::HTTP safely with it. Or maybe there is a way with Elevate to create periodic task.
Could you help me ?

Regards,

Julien

**Comment by mattgreen** [comment]
`Elevate::HTTP` is safe to use on any thread, but is only cancellable within the `task` block.

The periodic task block can call a method that then calls `async` like you would normally. Does that answer your question?
